enum EWSErrorDescription {
    'You need to login on pixelplace.io first. Create an account, it\'s free !',
    'Your session expired, please refresh the page',
    'You need to create a username first',
    'Color not found',
    'This color is only available to premium subscribers',
    'Wrong coordinates',
    'This canvas has been temporarily disabled because its owner used premium settings on it and his membership has expired. Please wait for the owner to renew his premium membership or to revert canvas settings to non premium ones',
    'Your premium membership has expired and this canvas is using premium settings. To continue, please renew your membership or revert canvas settings back to non premium ones',
    'Please wait until the end of your cooldown',
    'This canvas is private, you can\'t draw on it',
    'To be able to place pixels on this canvas, you have to request approval from the owner',
    'You are placing pixels too fast, please slow down',
    'This canvas is terminated',
    'Error while getting canvas data',
    'Error while getting canvas access data',
    'You have too many instances of pixelplace.io opened, please close some windows/tabs',
    'Too many users share your internet connection. If you are using a proxy or shared connection, you may need to switch to a private one or another proxy location',
    'Pixelplace.io has been disabled for your internet connection (are you  using a proxy ?)',
    'Server is full, please try again later',
    'Reloading..',
    'Your account has been temporarily disabled for placing pixels and/or sending messages too fast, try again in 5 minutes',
    'You need to be a Premium subscriber to draw on Prime Island',
    'User offline',
    'Servers full, please wait',
    'You need to be connected before sending messages',
    'You are sending messages too fast',
    'Your account is still suspended from the chat (temporarily)',
    'Your account is permanently banned from the chat, please contact moderators on discord or support@pixelplace.io if you need help',
    'You need to create a username before sending messages',
    'You are not allowed to send commands',
    'You need to join a Guild first',
    'You need to be a premium subscriber',
    'Painting archived',
    'Servers are full, we are limiting instances of pixelplace.io opened per user, please close some windows/tabs',
    'Servers are full, we are limiting instances of pixelplace.io opened per internet connections, please close some windows/tabs. If you are using a proxy or shared connection, you may need to switch to a private one or another proxy location',

};

export default EWSErrorDescription;